openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    Documentation for Books API, for Fugas practice course
    
    
    Some useful links:
    - [Books API Repository](https://github.com/codeRuslan/fugas-golang-practice)
  termsOfService: http://swagger.io/terms/
  contact:
    email: ruslanpilipyuk@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: localhost:8000
tags:
  - name: books
    description: Access to Book repository
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /books:
    get:
      tags:
        - books
      summary: Get existing books in repository
      description: -
      operationId: ReturnAllBooks
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BooksGet'
        '404':
          description: Books not found
    put:
      tags:
        - books
      summary: Put list of books into repository
      description: -
      operationId: CreateNewBook
      requestBody:
        description: Put list of books into repository
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BooksPut'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BooksPut'
        '404':
          description: Book not found
components:
  schemas:
    BooksGet:
      type: object
      properties:
        books:
          type: array
          example:
            - name: Rage
              author: Stephen King
              year: 1977
            - name: Philosopher's Stone
              author: J. K. Rowling
              year: 1997
            - name: All Quiet on the Western Front
              author: Erich Maria Remarque
              year: 1929
            - date: 02.01.2006
        items:
          type: object
          properties:
            name:
              type: string
            author:
              type: string
            year:
              type: integer
            date:
              type: string
              format: date
    BooksPut:
      type: object
      properties:
        books:
          type: array
          example:
            - name: Rage
              author: Stephen King
              year: 1977
            - name: Philosopher's Stone
              author: J. K. Rowling
              year: 1997
            - name: All Quiet on the Western Front
              author: Erich Maria Remarque
              year: 1929
            - date: 02.01.2006
        items:
          type: object
          properties:
            name:
              type: string
            author:
              type: string
            year:
              type: integer
            date:
              type: string
              format: date